### PR TITLE
fix(api): make PUT bookmark to a list idempotent

### LINKED ISSUE #1402: Add a bookmark to a list API should be idempotent
Adding bookmark to the list where it is already present returns 400 error, which prevents (or at least makes it more complicated) for exporters to work.

### PR DESCRIPTION
**Pull request by xuatz**
Fixes #1402

### CODE REVIEW

File: packages/trpc/models/lists.ts [hunk 1]
```diff
@@ -260,11 +260,10 @@ export class ManualList extends List {
...
       if (e instanceof SqliteError) {
         if (e.code == "SQLITE_CONSTRAINT_PRIMARYKEY") {
-          throw new TRPCError({
-            code: "BAD_REQUEST",
-            message: `Bookmark ${bookmarkId} is already in the list ${this.list.id}`,
-          });
+          // this is fine, it just means the bookmark is already in the list
+          return;
         }
+        console.error("Unhandled SqliteError");
```
Comment (MohamedBassem) [inline packages/trpc/models/lists.ts]: Can we remove this console log?

**Review by MohamedBassem — APPROVED** [review]
Thank you! 

Can you also update the openapi specs in `packages/open-api/lib/bookmarks.ts` and then run `pnpm generate` there to update the openapi specs?

File: packages/trpc/models/lists.ts (hunk 1 above)
Comment (xuatz) [reply packages/trpc/models/lists.ts]: sure 👍

File: packages/open-api/lib/lists.ts [hunk 2]
```diff
@@ -232,14 +232,6 @@ registry.registerPath({
...
       description: "No content - the bookmark was added",
     },
-    400: {
-      description: "Bookmark already in list",
-      content: {
-        "application/json": {
-          schema: ErrorSchema,
-        },
-      },
-    },
```
Comment (xuatz) [inline packages/open-api/lib/lists.ts:242]: @MohamedBassem I think you meant this file instead?

**Comment by MohamedBassem** [comment]
Thank you1
